services:
  - docker

before_install:
  - docker build -t danilucaci/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true danilucaci/docker-react npm run test -- --coverage

language: generic
